### PR TITLE
Constify all math functions

### PR DESCRIPTION
**Pull request by levitte**
This is supposed to bring this library to the same standards as other MPI libraries, and most of all, to be able to avoid all the deconstifying casts that currently happen in libtomcrypt when linking with tomsfastmath specifically.

### CODE REVIEW

**Comment by levitte** [comment]
Note that for this to be useful yet backward compatible, #36 needs to be merged as well.

I'm currently testing this with a cleaner libtomcrypt.  It will remain a draft until I'm satisfied that I got it all.

**Comment by levitte** [comment]
Also, this warrants updating the version to at least 0.14.0

**Comment by levitte** [comment]
It irritates me that `fp_exptmod` can't be entirely constified as it should...  I'll have think about that, 'cause that just shouldn't be.

**Comment by levitte** [comment]
> It irritates me that `fp_exptmod` can't be entirely constified as it should... I'll have think about that, 'cause that just shouldn't be.

Fixed it, it was much easier than anticipated

**Comment by levitte** [comment]
@sjaeckel, would you mind enabling workflows for me?

**Comment by levitte** [comment]
Oh, generators! I hadn't noticed those.... Thanks

**Comment by levitte** [comment]
I don't quite like the long line output of the generators, gotta admit.  But, that's work for another PR

**Comment by levitte** [comment]
Is this deemed complete by now?

**Review by sjaeckel — APPROVED** [review]
> I don't quite like the long line output of the generators, gotta admit. But, that's work for another PR

What? You don't like >50k char wide lines?

TBH I don't care since they're auto-generated and I'd leave it like that.

Thanks a lot for this PR!

**Comment by levitte** [comment]
> What? You don't like >50k char wide lines?

🤣

**Comment by levitte** [comment]
I saw you fixed all the end-of-line spaces.  Cool!

**Comment by levitte** [comment]
In my opinion, this can be merged as it currently stands

**Comment by levitte** [comment]
I would propose a version bump to 0.13.99 or something like that (implying that "next" is 0.14.0)

**Comment by sjaeckel** [comment]
Oh, I just realized ... we're not done here ... :(

`tfm.tex` is missing an update!

**Comment by levitte** [comment]
Oh!  Ok, I can fix that tomorrow (it being middle of the night here, it's sleep time)

**Comment by levitte** [comment]
Documentation updated

**Comment by levitte** [comment]
Anything else I've missed?

**Comment by sjaeckel** [comment]
> Anything else I've missed?

Nope, I've only rebased.

**Pull request merged**
